### ISSUE TITLE
Database Update

### ISSUE THREAD

**Issue by lintux** [Danysan1/open-etymology-map#3]
Hi and thanks for the great project. I added some etymology data in my OSM area and just recognized that the import of new data into the https://etymology.dsantini.it/ seems to be delayed (last on on Feg. 27th )
Is that a manual exercise or is the process broken?

BR
Stephan

**Comment by Danysan1** [comment]
Hi,
I imagine you are using the DB as source. The DB is updated with a semi-automatic process (which I have to trigger). The maximum frequence of update would be once a week (dictated by the [OSM planet.pbf](https://planet.openstreetmap.org/) release cycle), though it's usually lower (like once every two or three weeks).

If you need to see the data updated in real time you can use Overpass API as source, though it will be less complete:

![image](https://user-images.githubusercontent.com/8406735/226107188-d88ad69f-20c1-4ba1-93df-d704dcf11ec2.png)

![image](https://user-images.githubusercontent.com/8406735/226107888-e67c38eb-5cb4-49a0-a3b7-e89408e4ccac.png)

**Comment by Danysan1** [comment]
I have updated the DB data to 2023-03-20
