### ISSUE TITLE
name:etymology:wikidata on associatedStreet relation

### ISSUE THREAD

**Issue by Cyrille37** [Danysan1/open-etymology-map#4]
Hi.
Thanks for your really great work, it's impressive.

Some osm mappers use to attach tags on the associatedStreet relation rather than repeat them on each street segments. I think your tool does not read this tagging way. What is your opinion on the addition of this functionality?

**Comment by Danysan1** [comment]
I have long been interested in showing etymologies on relations with `type=street` or `type=associatedStreet`.

Unfortunately, these elements are lost from OSM dumps used for generating the pmtiles so I have no way to show them in the pmtiles back-end. [The same thing happens to most racetracks, as explained here](https://gitlab.com/openetymologymap/open-etymology-map/-/issues/12#note_1087473995):

> Both [the initialization script](https://gitlab.com/openetymologymap/open-etymology-map/-/blob/370d84e9d11c5af84f5a8f3e31e9afdefd4cf1ab/init/db-init.php#L652) and [Geofabrik](http://download.geofabrik.de/technical.html) do use osmium-export.
> From [Osmium documentation](https://docs.osmcode.org/osmium/latest/osmium-export.html) I read:
>
> >The export command transforms OSM data into a more usual GIS data model. Nodes will be translated into points and ways into linestrings or polygons (if they are closed ways). Multipolygon and boundary relations will be translated into multipolygons. This transformation is not loss-less, especially information in non-multipolygon, non-boundary relations is lost.
> 
> > Objects with invalid geometries are silently omitted from the output. This is the case for ways with less than two nodes or closed ways or relations that can’t be assembled into a valid (multi)polygon. See the options --show-errors/-e and --stop-on-error/-E for how to modify this behaviour.
>
> I guess this problem can't be solved downstream by me but only upstream in the pbf generation.

A similar technical problem happens with the Overpass back-end: Overpass API returns the relation, but then osm2geojson, which I use for transforming the Overpass response into GeoJSON (suitable for the map) it fails to transform it. For example, [this relation](https://www.openstreetmap.org/relation/13821051) is returned by Overpass [but I'm unable to show it](https://etymology.dsantini.it/#5.3681,43.2973,17.1,blue,overpass_all,stamen_toner):
![image](https://github.com/Danysan1/open-etymology-map/assets/8406735/fdca5409-67ca-4d0d-aee2-9b178cf2529e)

I believe these technical problems are outside of my ability to fix them (if you or anyone has suggestions on how to fix them, they are welcome), so in both cases unfortunately I can't show them :\

**Comment by Cyrille37** [comment]
Hi

With `https://overpass-turbo.eu` **exporting to geojson** (that use [osmtogeojson](https://github.com/tyrasd/osmtogeojson)) give all renderable data on a map.

The executable query in place on the map : http://overpass-turbo.eu/s/1LfI

```
// the "associatedStreet" relation "name=Rue de Jemmapes" has the tag "name:etymology:wikidata"
//
// [bbox:{{bbox}}];
[bbox:47.42450157940906,0.6815895438194275,47.42598052149432,0.6835716962814331]
(
  way["highway"="residential"]["name:etymology:wikidata"];
  relation["type"="associatedStreet"]["name:etymology:wikidata"];
);
(._;>;);
out body;
```

**Comment by Danysan1** [comment]
Hmm I will look again into that, maybe I lost some configuration...

**Comment by Danysan1** [comment]
I confirm that osmtogeojson is able to keep this data, I am now testing a new version that is able to render them, you can check it for example in https://owmf-test.wmcloud.org/#5.3694,43.2976,15.7,feature_source,overpass_all_etymology,stamen_toner_lite,etymology 

Once I have fixed some existing bugs I will push this fix to etymology.dsantini.it as well

**Comment by Cyrille37** [comment]
Great! Well done @Danysan1 :smile_cat: 

A proposal to refine: for `associatedStreet` relation removing role `house` will keep the map clearer and lighter.

![image](https://github.com/Danysan1/open-etymology-map/assets/368965/8cd634d0-3ad7-4286-8e69-739b9fc5a5da)

https://owmf-test.wmcloud.org/#0.6832,47.4244,15.0,feature_source,overpass_all_etymology,stamen_toner_lite,etymology

**Comment by Danysan1** [comment]
Right! Done! To check the new behaviour make sure to clean the cache:

![image](https://github.com/Danysan1/open-etymology-map/assets/8406735/9259531a-37bb-4f6d-9410-9086f7628b46)

**Comment by Cyrille37** [comment]
Fantastic! It works :-)

*In June I welcome trainees from secondary schools to find out more about the IT profession. I'm going to put them on the subject of OpenStreetMap and etymology, and your tool will be a perfect support* :-)

**Comment by Cyrille37** [comment]
After hours of work with OpenRefine :unicorn:  I'm running a mass update of `name:etymology:wikidata` in city "Tours in France" https://www.openstreetmap.org/user/Cyrille37Bot/diary/404117

**Comment by Danysan1** [comment]
Great! I updated all my OWMF instances (including https://etymology.dsantini.it ) to the new version (v3.1.2) which includes these changes to the relation handling
